# Generated by Django 5.1.3 on 2025-02-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
